import localFont from "next/font/local";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const vietnam = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-vietnam",
});

export const metadata = {
  title: "Digislash",
  description: "Generated by create next app",
  icons:{
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${vietnam.variable} antialiased `}
      >
        <Header/>
        <main className="">{children}</main>
        <Footer className="mt-0"/>
      </body>
    </html>
  );
}
