import localFont from "next/font/local";
import { Be_Vietnam_Pro } from "next/font/google";
// import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/themeProvide";
import { cn } from "@/lib/utils";
import Sidebar from "@/components/Dashboard/Sidebar";
// import { ThemeProvider } from "@/components/theme-provider";

const vietnam = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-vietnam",
});

export const metadata = {
  title: "Digislash",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function ({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          `min-h-screen w-full bg-white text-black flex ${vietnam.variable} antialiased `,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        {/* <p className="border">Sidebar</p> */}
        {/* <SideNavbar /> */}
         <Sidebar/>
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
